name: Test and Approve

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório para acessar o código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o ambiente para a versão do JDK 23 com distribuição temurin
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'  # Define a distribuição do JDK

      # Executa o Maven para construir e testar o projeto
      - name: Build and Test with Maven
        run: |
          ./mvnw clean install  # Comando que compila o projeto e roda os testes
